services:
  psh:
    container_name: psh-server-hub
    build:
      context: ..
      dockerfile: psh-docker/Dockerfile
    env_file:
      - .env
    environment:
      PSH_JWT_SECRET: ${PSH_JWT_SECRET}
      PSH_DEFAULT_USERNAME: ${PSH_DEFAULT_USERNAME}
      PSH_DEFAULT_PASSWORD: ${PSH_DEFAULT_PASSWORD}
      PSH_JWT_EXPIRE_MINUTES: ${PSH_JWT_EXPIRE_MINUTES}
    expose:
      - "9000"
    volumes:
      - psh_data:/app/psh-fastapi/data
    restart: unless-stopped
  nginx:
    container_name: psh-reverse-proxy
    build:
      context: .
      dockerfile: Dockerfile.nginx
    environment:
      PSH_PROTO_MODE: ${PSH_PROTO_MODE:-https}
    depends_on:
      - psh
    ports:
      - "${PSH_PROXY_HTTP_PORT:-9000}:80"
    restart: unless-stopped

volumes:
  psh_data:
